name: manually re-running actions Prod Deploy

on: 
  repository_dispatch:
     types: re-prod-deploy

jobs:
  manual_deploy:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
    - name: set AWS and Algolia Keys to environment
      env:
        GATSBY_ALGOLIA_APP_ID: ${{ secrets.GATSBY_ALGOLIA_APP_ID}}
        GATSBY_ALGOLIA_SEARCH_KEY: ${{secrets.GATSBY_ALGOLIA_SEARCH_KEY}}
        ALGOLIA_ADMIN_KEY: ${{secrets.ALGOLIA_ADMIN_KEY}}
        AWS_ACCESS_KEY_ID: ${{secrets.PROD_AWS_ACCESS_KEY_ID}}
        AWS_SECRET_ACCESS_KEY: ${{secrets.PROD_AWS_SECRET_ACCESS_KEY}}
        DIST_ID: ${{secrets.PROD_DIST_ID}}
        MUNCHKIN_ID: ${{ secrets.MUNCHKIN_ID}}
        NEWSLETTER_FORM_ID: ${{secrets.NEWSLETTER_FORM_ID}}
      run: |
        npm install
        npm run build:prod && node_modules/s3-deploy/bin/s3-deploy './public/**' --cwd './public/' --bucket postman-blog-prod --deleteRemoved --private --distId $DIST_ID --invalidate '/*'
        